// Client/react-js/src/app/controls/components/form.hidden.component.tsx
import React from 'React';
import { BaseControlComponent } from './base.control.component';
export class FormHidden extends BaseControlComponent {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div>
                    <input type={this.props.type}
                        value={this.state.value as string}
                        disabled = {this.isDisabled()} />
                </div>
        )
    }
}

// Client/Angular/src/app/controls/components/form-hidden/form-hidden.component.ts
import { Component, OnInit } from '@angular/core';
import { BaseControlComponent } from '../base-control-component/base.control.component';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-form-hidden',
  templateUrl: './form-hidden.component.html',
  styleUrls: ['./form-hidden.component.scss']
})
export class FormHiddenComponent extends BaseControlComponent {

  constructor(fb: FormBuilder) {
    super(fb);
   }
}

<div [formGroup]="group">
    <input [type]="type" [attr.disabled]="isDisabled()" [formControlName]="name"/>
</div>
