// Client/react-js/src/app/controls/components/form.input.component.tsx
import React from 'React';
import { BaseControlComponent } from './base.control.component';
export class FormInput extends BaseControlComponent {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div className="form-group row">
                <label className={this.state.uiProps.labelWidth}> {this.props.label} </label>
                <div className={this.state.uiProps.controlWidth}>
                    <input type={this.props.type}
                        className={this.state.uiProps.cssClass}
                        placeholder={this.props.placeholder}
                        value={this.state.value as string}
                        onChange={this.handleChange} 
                        disabled = {this.isDisabled()} />
                </div>
            </div>
        )
    }
}

// Client/Angular/src/app/controls/components/form-input/form-input.component.ts
import { Component } from '@angular/core';
import { BaseControlComponent } from '../base-control-component/base.control.component';
import { FormBuilder } from '@angular/forms';
@Component({
  selector: 'app-form-input',
  templateUrl: './form-input.component.html',
  styleUrls: ['./form-input.component.scss']
})
export class FormInputComponent extends BaseControlComponent {
  constructor(fb: FormBuilder) {
    super(fb);
   }
}


  <div class="form-group row" [ngClass]="containerCss" [formGroup]="group">
    <label [ngClass]="labelWidth">{{ label | translate }}</label>
    <div [ngClass]="controlWidth">
      <input [type]="type" [ngClass]="cssClass" [attr.disabled]="isDisabled()" [attr.placeholder]="placeholder" [formControlName]="name"
        [value]="value">
      <form-display-errors [errors]="this.control.errors"></form-display-errors>
    </div>
  </div>
