// Client/react-js/src/app/controls/components/base.control.component.ts
import React from 'React';
import { Option, TypeaheadOptions, FormModel, DatetimePickerOptions, CatalogData } from '../models';
import { isArray } from 'util';
interface IProps {
    type: string;
    name: string;
    disabled?: boolean;
    label?: string;
    options?:string[]| Option[];
    placeholder?: string;
    value?: string| CatalogData;
    cssClass?: string;
    typeaheadOptions?: TypeaheadOptions;
    datetimePickerOptions?: DatetimePickerOptions;
    formModel: FormModel;
    containerCss: string;
}
interface IState {
    uiProps: {
        labelWidth: string;
        controlWidth: string;
        cssClass: string;
        containerCss?:string;
    }
    options?: Option[];
    value: string | CatalogData;
}

export class BaseControlComponent extends React.Component<IProps, IState> {
    constructor(public props: IProps) {
        super(props);
        this.defaultUIConfig();
        this.handleOptions();
    }
    public defaultUIConfig() {
        this.setState({
            uiProps: {
                labelWidth: 'col-sm-12 col-md-2 col-form-label',
                controlWidth: 'col-sm-12 col-md-10',
                cssClass: this.props.cssClass || 'form-control'
            }
        });
    }
    public handleOptions() {
        if (this.props.options && this.props.options.length > 0) {
            let options:Option[] = null;
            if (isArray(this.props.options) && typeof (this.props.options[0]) === 'string') {
                options = (this.props.options as string[]).map(this.stringToOptions) as Option[];
            } else {
                options = this.props.options as Option[];
            }
            this.setState({options,value:''});
        }
    }
    public handleChange(event) {
        this.setState({value: event.target.value});
    }
    public  isDisabled(){
        return this.props.formModel.isLocked || this.props.disabled;
    }
    private stringToOptions = str => { return {label: str, value: str } }; 
}

// Client/Angular/src/app/controls/components/base-control-component/base.control.component.ts

import { FormGroup, ValidatorFn, AbstractControl, FormBuilder } from '@angular/forms';
import { OnInit, Input } from '@angular/core';
import { Option, CustomValidations, FormModel, Error, IDatetimePickerOptions, TypeaheadOptions } from '../../../biz-os-shared';
export class BaseControlComponent implements OnInit {

  labelWidth: string;
  controlWidth: string;
  constructor(private fb: FormBuilder) {
    this.labelWidth = 'col-sm-12 col-md-2 col-form-label';
    this.controlWidth = ' col-sm-12 col-md-10';
  }
  @Input()
  type: string;
  @Input()
  name: string;
  @Input()
  disabled?: boolean;
  @Input()
  label?: string;
  @Input()
  options?: Option[] | string[] ;
  @Input()
  placeholder?: string;
  @Input()
  errors?: Error[];
  @Input()
  validation?: ValidatorFn[];
  @Input()
  customValidation?: CustomValidations;
  @Input()
  value?: any;
  @Input()
  cssClass?: string;
  @Input()
  typeaheadOptions?: TypeaheadOptions;
  @Input()
  datetimePickerOptions?: IDatetimePickerOptions;
  @Input()
  formModel: FormModel;
  @Input()
  containerCss: string;

  group: FormGroup;
  control: AbstractControl;
  ngOnInit() {
    this.defaultConfig();
    const controls = {};
    controls[this.name] = {};
    this.group = this.group || this.fb.group(controls);
    this.value = this.value || '';
    this.control = this.group.get(this.name);
  }

  defaultConfig(): void {
    this.cssClass = this.cssClass || 'form-control';
  }

  handleOptions(): void {
    if (this.options && this.options.length > 0 && typeof(this.options[0]) === 'string' ) {
      this.options = (this.options as string[]).map((option: string) => {
        return  {label: option, value: option} as Option;
     });
    }
  }
  isDisabled(): boolean {
    return (this.disabled
     || (this.formModel && this.formModel.isLocked)) ? true : undefined;
      // || (this.formModel && this.formModel.formMode === FormMode.Update && (this.control as any).isUpdatable);
  }
  hasError(): boolean {
    return this.errors && this.errors.length > 0;
  }
}
