// Client/Angular/src/app/controls/components/form-radio/form-radio.component.ts
import { Component, OnInit } from '@angular/core';
import { BaseControlComponent } from '../base-control-component/base.control.component';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-form-radio',
  templateUrl: './form-radio.component.html',
  styleUrls: ['./form-radio.component.scss']
})
export class FormRadioComponent extends BaseControlComponent implements OnInit {

  constructor(fb: FormBuilder) {
    super(fb);
  }

  ngOnInit() {
    this.defaultConfig();
    this.handleOptions();
  }

}

<div class="form-check" [ngClass]="containerCss" [formGroup]="group">
    <legend class="col-form-label" [ngClass]="labelWidth">{{ label | translate }}</legend>
  <div [ngClass]="controlWidth">
    <div *ngFor="let option of options">
      <input type="radio" class="form-check-input" [ngClass]="cssClass" [value]="option.value" [attr.name]="name" [attr.disabled] = "isDisabled()" [formControlName]="name" [attr.disabled]="option.disabled">
      <label class="form-check-label">  
        {{option.label}}
      </label>
    </div>
    <form-display-errors [errors]="errors"></form-display-errors>
  </div>
</div>

// Client/react-js/src/app/controls/components/form.radio.component.tsx
import React from 'React';
import { BaseControlComponent } from './base.control.component';
export class FormRadio extends BaseControlComponent {
    constructor(props) {
        super(props);
    }

    render() {
        let radioConrtols = this.state.options.map(option => {

            <label className="form-check-label">
                <input type="radio"
                    className={"form-check-input" + this.state.uiProps.cssClass}
                    value={option.value}
                    name="name"
                    disabled={this.isDisabled() || option.disabled} />
                {option.label}
            </label>
        });
        return (
            <div className={"form-check" + this.state.uiProps.containerCss}>
                <legend className={ "col-form-label" + this.state.uiProps.labelWidth}>{this.props.label}</legend>
                <div className={this.state.uiProps.controlWidth}>
                    <div>
                        {radioConrtols}
                    </div>
                </div>
            </div>
        )
    }
}
