// Client/Angular/src/app/controls/components/form-checkbox/form-checkbox.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { BaseControlComponent } from '../base-control-component/base.control.component';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-form-checkbox',
  templateUrl: './form-checkbox.component.html',
  styleUrls: ['./form-checkbox.component.scss']
})
export class FormCheckboxComponent extends BaseControlComponent implements OnInit {

  constructor(fb: FormBuilder) {
    super(fb);
  }

  ngOnInit() {
    this.cssClass = this.cssClass || '  ';
    this.defaultConfig();
  }

}

<div class="form-check" [ngClass]="containerCss" [formGroup]="group">
  <div [ngClass]="controlWidth" class="offset-m3">
      <input type="checkbox" class="form-check-input" [ngClass]="cssClass" [attr.disabled]="isDisabled()" [formControlName]="name" />
      <label class="form-check-label">
       {{label | translate}}
    </label>
    <form-display-errors [errors]="errors"></form-display-errors>
  </div>
  
</div>

// Client/react-js/src/app/controls/components/form.checkbox.component.tsx
import React from 'React';
import { BaseControlComponent } from './base.control.component';
export class FormCheckbox extends BaseControlComponent {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div className={"form-check" + this.state.uiProps.containerCss}>
                <div className={"offset-m3" + this.state.uiProps.controlWidth}>
                    <div>
                    <input type="checkbox"
                    className={"form-check-input" + this.state.uiProps.cssClass}
                    value={this.state.value as string}
                    name="name"
                    disabled={this.isDisabled() } />
                
                    <label className="form-check-label">
                    {this.props.label}
            </label>
                    </div>
                </div>
            </div>
        )
    }
}
