// Client/Angular/src/app/controls/components/form-select/form-select.component.ts
import { Component, OnInit } from '@angular/core';
import { BaseControlComponent } from '../base-control-component/base.control.component';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-form-select',
  templateUrl: './form-select.component.html',
  styleUrls: ['./form-select.component.scss']
})
export class FormSelectComponent extends BaseControlComponent implements OnInit {

  constructor(fb: FormBuilder) {
    super(fb);
  }

  ngOnInit() {
    this.defaultConfig();
    this.handleOptions();
  }
}

<div class="form-group row" [ngClass]="containerCss" [formGroup]="group">
  <label [ngClass]="labelWidth">{{ label | translate }}</label>
  <div [ngClass]="controlWidth">
    <select [ngClass]="cssClass" [formControlName]="name" [attr.disabled]="isDisabled()">
      <option value="">{{ placeholder }}</option>
      <option [attr.value]="option.value" [attr.disabled]="option.disabled" *ngFor="let option of options">
        {{ option.label }}
      </option>
    </select>
    <form-display-errors [errors]="errors"></form-display-errors>
  </div>
</div>

// Client/react-js/src/app/controls/components/form.select.component.tsx
import React from 'React';
import { BaseControlComponent } from './base.control.component';

export class FormSelect extends BaseControlComponent {
    constructor(props) {
        super(props);
    }
    render() {
        const options = this.state.options.map(option => {
            return (<option value="option.value" >
                {option.label}
            </option>);
        });
        return (
            <div className={"form-group row " + this.props.containerCss}>
                <label className={this.state.uiProps.labelWidth}>{this.props.label}</label>
                <div className={this.state.uiProps.controlWidth}>
                    <select value={this.state.value as string}
                        onChange={this.handleChange}
                        className={this.state.uiProps.cssClass}
                        disabled={this.isDisabled()}
                    >
                        <option value="">{this.props.placeholder}</option>
                        {options}
                    </select>
                </div>
            </div>
        );
    }

}
