// Client/react-js/src/app/controls/components/form.textarea.component.tsx

import React from 'react';
import { BaseControlComponent } from './base.control.component';
export class FormTextarea extends BaseControlComponent {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div className="form-group row">
                <label className={this.state.uiProps.labelWidth}> {this.props.label} </label>
                <div className={this.state.uiProps.controlWidth}>
                    <textarea
                        className={this.state.uiProps.cssClass}
                        placeholder={this.props.placeholder}
                        value={this.state.value as string}
                        onChange={this.handleChange}
                        disabled = {this.isDisabled()}
                         />
                </div>
            </div>
        )
    }
}

// Client/Angular/src/app/controls/components/form-textarea/form-textarea.component.ts
import { Component, OnInit } from '@angular/core';
import { BaseControlComponent } from '../base-control-component/base.control.component';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-form-textarea',
  templateUrl: './form-textarea.component.html',
  styleUrls: ['./form-textarea.component.scss']
})
export class FormTextareaComponent extends BaseControlComponent {

  constructor(fb: FormBuilder) {
    super(fb);
  }
}

<div class="form-group row" [ngClass]="containerCss" [formGroup]="group">
  <label [ngClass]="labelWidth">{{ label | translate }}</label>
  <div [ngClass]="controlWidth">
    <textarea class="form-control" [formControlName]="name" [attr.disabled]="isDisabled()" [attr.placeholder]="placeholder">
  </textarea>
    <form-display-errors [errors]="errors"></form-display-errors>
  </div>

</div>
